name: Create and deploy javadoc

# TODO: create folders for each version and deploy the files to the corresponding version folder
# You can prbly use the variable $GITHUB_REF

on:
  registry_package:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v4
      with:
        repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/${GITHUB_REPOSITORY}"}]'
        servers: '[{ "id": "github", "username": "x-access-token", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
    - name: Build with Maven
      run: mvn -B javadoc:javadoc --file pom.xml
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: javadoc
        path: target/site/
    - name: Checkout gh-pages
      uses: actions/checkout@v2.0.0
      with:
        ref: gh-pages
    - run: rm -rf javadoc
    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: javadoc
        path: tmp
    - run: mv tmp/apidocs javadoc && rm -rf tmp
    - run: wget -O README.md https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/master/README.md
    - name: Commit
      uses: zwaldowski/git-commit-action@v1
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        tags: false
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}